apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: default
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: eureka:1.0.7
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
