server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka.default:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true


