spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    registerWithEureka: false
#    fetchRegistry: false
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO



#eureka:
#  instance:
#    hostname: eureka
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
