apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
  namespace: default
  labels:
    app: microservice-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
        - name: microservice-b
          image: microservice-b:1.0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
